#-----------------------------------#
#              H I N T S            #
#-----------------------------------#

# -- The list of fields to be used in sign-format --
# %PLAYER%		- Owner of the island
# %NUMBER%		- Top number of the island
# %VALUE%		- Value of the island
# %MEMBERS%		- How many members the island has
# %NAME%		- Name of the island
# %ID%			- ID of the island
# %ONISLAND%	- How many players are on the island right now
#
# -- The list of fields to be used everywhere --
# %RAQUO% 		- Right guillement
# %LAQUO%		- Left guillement
# %REG%			- Registered trademark (whoever needs it)
# %COPY%		- Copyright (whoever needs it)
# %PARAGRAPH%	- A paragraph character
# %APOSTROPHE%	- An apostrophe

# If you would need to use an apostrophe inside of a message / sign format,
# use %APOSTROPHE% instead. In case you will use ' instead of apostrophe field,
# you will get a YAML parse error.

# Use the '&' character as prefix for color codes.
# Example: &aHello, world!

#-----------------------------------#
#           M E S S A G E S         #
#-----------------------------------#

msg-prefix: '&b&lIridiumScoreBoard&8 %LAQUO%&r '
msg-no-permission: '&cYou don%APOSTROPHE%t have permission to do that.'
msg-no-console: '&cYou must be a player to execute this command.'
msg-panel-add: '&aThe score panel was added to the list.'
msg-panel-clear: '&aAll panels have been removed.'
msg-not-sign: '&cThe selected block is not a sign.'
msg-test: '&aAll panels have been filled with test content.'
msg-test-bad-block: '&cEncountered a block which is not a sign while testing the scoreboard. Skipped.'
msg-stop: '&aAll update tasks have been stopped. The scoreboard won%APOSTROPHE%t refresh until /isbstart was called.'
msg-start: '&aA new score board update process has just started.'
msg-saved: '&aSaved.'
msg-reloaded: '&aConfig reloaded.'
msg-private: '&cThis island is private.'
msg-whoosh: '&aWhoosh!'
msg-reset-done: '&aConfig reset.'

#-----------------------------------#
#              S I G N S            #
#-----------------------------------#

sign-format:
  - ''
  - '&2&lTOP %NUMBER%'
  - '&7%PLAYER%'
  - '&a%VALUE%'

sign-empty-format:
  - ''
  - ''
  - ''
  - ''

#-----------------------------------#
#        P E R M I S S I O N S      #
#-----------------------------------#

signtp-bypasspermission: true
