name: IridiumScoreBoard
main: org.piotrwyrw.iridiumscoreboard.Main
depend: [IridiumSkyblock]
version: 1.3
author: piotrwyrw
api-version: 1.15
commands:
  isbadd: 
    description: Add a score panel to the score board.
  isbtest: 
    description: (Temporary) Test the score board system.
  isbclear:
    description: Remove all score panels.
  isbsave:
    description: Save current panels to a file.
  isbstop:
    description: Stop all updating tasks.
  isbstart:
    description: Start a new updating process.