name: IridiumScoreBoard
main: org.piotrwyrw.iridiumscoreboard.IridiumScoreBoard
description: '1.16.1'
depend: [IridiumSkyblock]
version: 1.8
author: piotrwyrw
api-version: 1.15
commands:
  isb:
    description: Main command